# forward migrate
[[redirects]]
  from = "https://migrate.uniswap.ch/*"
  to = "https://uniswap.ch/migrate/v1"
  status = 301
  force = true

# forward v2 subdomain to apex
[[redirects]]
  from = "https://v2.uniswap.ch/*"
  to = "https://uniswap.ch/:splat"
  status = 301

# support SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
